# Generated by Django 4.1 on 2022-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'ordering': ['fruit_name'], 'verbose_name': 'home_fruits'},
        ),
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together={('fruit_name', 'price')},
        ),
        migrations.AlterModelTable(
            name='fruits',
            table='home_fruits',
        ),
    ]
